### ISSUE TITLE
Vertical resize not working on Linux AppImage

### ISSUE THREAD

**Issue by hialvaro** [loki-project/session-desktop#1114]
**Describe the bug**
I'm unable to resize the Linux AppImage to fit my screen vertically.

**To Reproduce**
Download the latest AppImage for Linux. Open the AppImage and see that it is not resizing like it should.

**Expected behaviour**
Open the AppImage with a size that fits the screen. If it opens with a bigger size, user should be able to resize it.

**Screenshots or Logs**
[Gif with described issue](https://imgur.com/YLbUIiU)

**Other information (please complete the following information):**

* Device: PC
* OS: Arch Linux
* Session Version or Git commit hash: Latest version downloaded today from https://getsession.org/download

**Comment by JamesKni** [comment]
What resolution is your display?

**Comment by armonraze** [comment]
Hi..I have the same problem. Im using Linux Mint and my resolution is 1366 x 768(16:9) , I also have tryed to change it but it didn't work. I cannot even write because the message section is under the bottom line of the screen. It is a pity because this app was reeeallly cool... do you have any idea on how to fix it?

**Comment by JamesKni** [comment]
It's because the minimum height for the window is at 820, so you aren't able to resize it to be smaller than that at the moment. Here is the issue to follow https://github.com/loki-project/session-desktop/issues/820. I went ahead and forked it and changed the value to something lower myself, so if you really need it then you can get that, but it's probably best to just wait.

**Comment by armonraze** [comment]
Please can you link me the guidt so i can try to fix it myself? Is it really complicated?? 
Thanks for your patience.

**Comment by hialvaro** [comment]
@JamesKni my resolution is 1366 x 768

**Comment by JamesKni** [comment]
@armonraze There is no guide, you can take a look at what I did for it on my Github to see what I did or just download it from there (from the commit, not the releases)

@hialvaro That's the same problem then. Best thing to do is wait for it to be fixed or you can follow what I said above

**Comment by AndyMc47** [comment]
I'm experiencing same issue on Ubuntu 20.04 with screen resolution 1920x1080 and Font Scaling Factor 1.5 - where I have no resize option and the bottom of the app is below the screen.

If I set Font Scaling Factor to 1.0 before starting the app then it works fine. And once it's started I can change Font Scaling Factor back to 1.50 and the app resizes and still works fine (I can resize and see the bottom of the app). So it's just on startup where I'm getting an issue.

**Comment by KeeJef** [comment]
#1142 Should make this a little better, allowing down to 600 px min height
