### ISSUE TITLE
Keyboard selection via Shift not working when starting a selection from the right

### ISSUE THREAD

**Issue by jagerman** [loki-project/session-desktop#631]
**Describe the bug**
When using Shift-Left to start selecting test I have just typed I don't start a selection.  What's odd is that if I move to the left and then use Shift-Right it *does* start a selection, and Shift-Left once there is such a selection reduces the selection; it just won't start it.

(This combines with #630 to break Ctrl-Shift-Left, which I use all the time for inline editing).

**To Reproduce**
Type some test, press Shift-Left.

**Other information (please complete the following information):**

* Device: PC
* OS: Debian sid
* Loki messenger Version or Git commit hash: v1.0.0-beta8

**Comment by Bilb** [comment]
Had a small look at this issue a few days ago.
Looks like in Debian sid (my case too), the direction field in the event is not correctly set. Don't know why.
When using the left arrow with a selection already set, the event is sent with a direction as "forward" but should be "backward" I think. (maybe check on other platforms the direction for this case).

Something like that would fix this issue, but maybe there is a root cause somewhere else. Any ideas? 

```
+++ b/js/views/conversation_view.js
@@ -2444,9 +2444,8 @@
       let direction = $input.selectionDirection;

       if (event.shiftKey) {
-        if (direction === 'none') {
+        if (direction === 'none' || direction === 'forward') {
           if (isLeft) {
             direction = 'backward';
           } else {
```
