### ISSUE TITLE
Sealed sender

### ISSUE THREAD

**Issue by sachaaaaa** [loki-project/session-desktop#92]
Sealed senders is a feature from Signal.
We need to investigate if/how we want to integrate that as well in Loki messenger.

**Comment by KeeJef** [comment]
Just want to ping this as Beau and I had a discussion about this in the office. It seems that Sealed Sender is enabled on Mobile devices so we should probably look there for some clues on implementation. Especially since our "Servers" are operating as much less trusted than Signals servers are, and giving them access to Sender info is less than optimal

**Comment by KeeJef** [comment]
Status on this? @sachaaaaa

**Comment by sachaaaaa** [comment]
No progress unfortunately, I guess we need to bump this up in priority if we want anything done with sealed senders.
