### ISSUE TITLE
not the same seed, same session ID

### ISSUE THREAD

**Issue by boistordu** [loki-project/session-desktop#961]
**Describe the bug**
Is it normal that I don't get the same seed from my iphone and from my PC for the same session ID? or should I unlink then relink again since the update to 1.0.4 from 1.0.2?

**Other information (please complete the following information):**

* Device: [e.g. PC, Mac] PC
* OS: [e.g. Ubuntu 16.04, Windows 10] Win10
* Session Version or Git commit hash: 1.0.4

**Comment by KeeJef** [comment]
This should be fixed in the latest desktop release, Desktop releases (pre-1.0.4) were producing seeds that could not be restored on any other platforms. 1.0.4 should now be inline with mobile releases and the seeds should be compatible with all platforms. If you had created a Session seed with a desktop client pre 1.0.4 you will need to create a new session account to allow you to restore your seed on all platforms.

**Comment by boistordu** [comment]
I think you have missed a lot of information and context here.

First I have upgrade from 1.0.2 to 1.0.4.
Second The session has been created on iOS first!!!! Then I've tried to link up my pc.
everything is up to date. the session Id linking works.
not the recovery phrase.
I REPEAT: the session has been first CREATED ON IOS. NOT ON PC.

So does it mean that even on IOS it was buggy and so I need to erase the account and begin from scratch again ?
Best regard

**Comment by KeeJef** [comment]
Oh yeah i think i misunderstood this, Yes that's normal, since when you link two devices they actually have different seeds, but the secondary device always shows the primary devices Session ID. This ensures that when you give your Session ID to someone else they dont add your secondary devices public key.

**Comment by boistordu** [comment]
I don't understand your concept of restore then.
You can't recover anything from your seed. What can you actually restore from your seed?
I've tried to restore after an uninstallation of the windows client for example just to see and it didn't restore any data at all, it gave me a different session ID even that the one I had before. 

Restoring should be, having your data back or restoring would be giving you access to the same account id than before which is here a session ID.
It's not the case.
I can understand that the data could not be recover because it is only available on peripherals. Fine okey. But then it should be giving me the same session ID than before so that contacts can talk to me again. It's apparently not the case.   

Is it just to restore private/public keys? because if is, then I clearly not see the point if it's changing the session ID. Because this means that contacts don't have your information anymore if you change your session ID

**Comment by KeeJef** [comment]
Restoration should restore your identity, not your data. You should only be able to get your seed phrase from your primary device. if you restore this then you should keep the same Session ID as you had before

**Comment by boistordu** [comment]
okey thanks for that clarification. Ad thanks for having confirmed on the community chat that it was a bug in previous version of desktop client. By chance I didn't loose anything
