### ISSUE TITLE
Friend requests pre-approved

### ISSUE THREAD

**Issue by vincentbavitz** [loki-project/session-desktop#989]
To reproduce:
User A sends a friend request to User B.
User B opens friend requests list from LeftPane contacts section
User A sees friend request ACCEPTED before user B clicks "accept" or "decline".

When user B clicks "decline", the conversation is deleted for user B while user A still sees "Friend request accepted" on their chat screen.

![Screenshot_20200319_131650](https://user-images.githubusercontent.com/58160433/77025818-31602300-69e6-11ea-8df6-21d26aa5c4fd.png)
![Screenshot_20200319_132052](https://user-images.githubusercontent.com/58160433/77025821-32915000-69e6-11ea-8713-f643183c3c47.png)

**Comment by vincentbavitz** [comment]
![image](https://user-images.githubusercontent.com/58160433/77388187-808dc580-6de3-11ea-9b7b-76d984c60640.png)

**Comment by Brice-W** [comment]
I ran the following test from Android: (Desktop here means either Windows and MacOS versions)
Sending a first message to Desktop (= friend request). I just waited, no action on either sides, the Desktop received the request and then it got accepted automatically on Android, but was still pending on Desktop.
Then I could send other messages from Android, and they were displayed on the Desktop. I couldn’t write back from Desktop as the friend request was still pending.
If I Decline the request on the Desktop, the conversation disappears on the Desktop, but I am still able to message from Android. When I send more messages from Android, it makes the conversation coming back on Desktop, and I can write back from Desktop to Android, even if I declined before.

I ran that same test with iOS instead of Android, and between 2 Desktop, observing the same behaviour.
